todoapp/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'todoapp'
urlpatterns = [
	path('', views.index, name='index'),
	path('general_tasks/', views.general_tasks, name='general-tasks'),
	path('general_tasks/edit_list/', views.edit_list, name='edit-list'),
	path('general_tasks/remove_list/', views.remove_list, name='remove-list'),
	path('<int:list_id>/', views.todo_item, name='items'),
	path('edit_item/', views.edit_item, name='edit-item'),
	path('remove_item/', views.remove_item, name='remove-item'),
	path('item_toggle_check/', views.item_toggle_check, name='item-toggle-check'),
	path('task_toggle_check/', views.task_toggle_check, name='task-toggle-check'),
	path('item_is_checked/', views.item_is_checked, name='item-is-checked'),
	path('task_is_checked/', views.task_is_checked, name='task-is-checked'),
	path('get_max_date/', views.get_max_date, name='get-max-date'),
	path('general_tasks/task_done/', views.task_done, name='task-done'),
	path('get_task_title/', views.get_task_title, name='get-task-title'),
	path('signup/', views.signup, name='signup'),
	path('login/', auth_views.LoginView.as_view(template_name='todoapp/login.html'), name='login'),
	path('logout/', auth_views.LogoutView.as_view(template_name='todoapp/logout.html'), name='logout'),
]

todolist/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
	path('', include('todoapp.urls')),
    path('admin/', admin.site.urls),
	path('', include('social_django.urls', namespace='social')),
]

todoapp/models.py
from django.db import models
from django.contrib.auth.models import User


class ToDoList(models.Model):
	
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	title = models.CharField(max_length=300)
	deadline = models.DateField()
	done = models.BooleanField(default=False)	 #If the "done" field of all its items = done --> True
	hasItem = models.BooleanField(default=False) #If a task doesn't have any items, it should be considered in the user's calendar itself.
	
	def __str__(self):
		return self.title
		
#Each list could have some to-do-items.		
class ToDoItem(models.Model):
	
	todolist = models.ForeignKey(ToDoList, on_delete=models.CASCADE)
	title = models.CharField(max_length=300)
	date_to_do = models.DateField(null=True, blank=True)
	time_to_do = models.TimeField(null=True, blank=True)
	done = models.BooleanField(default=False)
	important = models.BooleanField(default=False)
	
	def __str__(self):
		return self.title
		

todoapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

todoapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt
from django.utils import timezone

from django.contrib import messages
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .forms import SignUpForm
from .models import ToDoList, ToDoItem

import datetime


#To display items of each day, week, or month
@login_required
def index(request):

	today = timezone.now().date()
	current_week = today.strftime("%V")
	current_month = today.month
	
	daily_task = ToDoList.objects.filter(deadline=str(today),hasItem=False).order_by('done','deadline')
	daily_task = daily_task.filter(user=User.objects.get(id=request.user.id))
	daily_list = ToDoItem.objects.filter(date_to_do=str(today)).order_by('done','time_to_do','-important')
	daily_list = daily_list.filter(todolist__user=User.objects.get(id=request.user.id))
	
	weekly_task = ToDoList.objects.filter(deadline__week=current_week,hasItem=False).order_by('done','deadline')
	weekly_task = weekly_task.filter(user=User.objects.get(id=request.user.id))
	weekly_list = ToDoItem.objects.filter(date_to_do__week=current_week).order_by('done','date_to_do','-important','time_to_do')
	weekly_list = weekly_list.filter(todolist__user=User.objects.get(id=request.user.id))
	
	monthly_task = ToDoList.objects.filter(deadline__month=current_month, hasItem=False).order_by('done','deadline')
	monthly_task = monthly_task.filter(user=User.objects.get(id=request.user.id))
	monthly_list = ToDoItem.objects.filter(date_to_do__month=current_month).order_by('done','date_to_do','-important','time_to_do')
	monthly_list = monthly_list.filter(todolist__user=User.objects.get(id=request.user.id))
	
	return render(request, "todoapp/index.html", {"daily_list": daily_list, "weekly_list": weekly_list, "monthly_list": monthly_list,"daily_task": daily_task, "weekly_task": weekly_task, "monthly_task": monthly_task})
	

#To display list of general Tasks
def general_tasks(request):
	
	todolist = ToDoList.objects.all()
	
	if request.method == "POST":
		
		if "save" in request.POST:
			title = request.POST["title"]
			deadline = request.POST["deadline"]
			user = User.objects.get(id=request.user.id)
			ToDo = ToDoList(user=user,title=title,deadline=deadline)
			ToDo.save()
			return redirect("/general_tasks")
		
	return render(request, "todoapp/general.html", {"todolist": todolist})
			

#To remove a todolist from database
@csrf_exempt
def remove_list(request):
	
	list_id = request.POST.get('listid', None)
	
	removed_list = ToDoList.objects.get(pk=list_id)
	removed_list.delete()
	
	data = {'is_removed': True}
	
	return JsonResponse(data)
	

# To edit date or title of a todolist
@csrf_exempt
def edit_list(request):

	new_title = request.POST.get("titleValue",None)
	new_date = request.POST.get("dateValue", None)
	list_id = request.POST.get("listId", None)
		
	edited_list = ToDoList.objects.get(pk=list_id)
	edited_list.title = new_title
	
	if new_date != "":
		edited_list.deadline = new_date
	
	ret_data = {'new_date': edited_list.deadline}
	
	edited_list.save();
		
	return JsonResponse(ret_data);

	
# To display items of a todolist and to show that if items have done or not
def todo_item(request, list_id):

	todolist = ToDoList.objects.get(id=list_id)
	
	todoitems = ToDoItem.objects.filter(todolist=list_id)
	step_number = todoitems.count() + 1
	
	context = {"todoitems": todoitems, "todolist":todolist, "step_number":step_number}
	
	if request.method == "POST":
		
		if "save" in request.POST:
			
			to_do_name = request.POST["title"]
			date_to_do = str(request.POST["due_date"])
			time_to_do = None
			
			if request.POST["due_time"] is not '':
				time_to_do = str(request.POST["due_time"])

			if request.POST.get("important", None):
				important = True
			else:
				important = False
				
			item = ToDoItem(todolist_id=list_id,title=to_do_name,date_to_do=date_to_do,time_to_do=time_to_do,important=important)
			item.save()
			
			items_count = ToDoItem.objects.filter(todolist_id=list_id).count()
			checked_items_count = ToDoItem.objects.filter(done=True, todolist_id=list_id).count()
	
			if items_count == checked_items_count:
				todolist.done = True;
			else:
				todolist.done = False;
		
			todolist.hasItem = True
			
			todolist.save();
			
			return redirect("/"+str(list_id))
		
	return render(request, "todoapp/items.html", context)
	

#To remove an item and update both ToDoList and ToDoItem tables
@csrf_exempt
def remove_item(request, list_id=None):
	
	todo_id = request.POST.get('todoid', None)
	
	removed_item = ToDoItem.objects.get(pk=todo_id)
	todo_list_id = removed_item.todolist_id; 
	removed_item.delete()
	
	items_count = ToDoItem.objects.filter(todolist_id=todo_list_id).count()
	step_number = items_count + 1;
	
	checked_items_count = ToDoItem.objects.filter(done=True, todolist_id=todo_list_id).count()
	
	parent_list = ToDoList.objects.get(pk=removed_item.todolist_id)
	if items_count == checked_items_count:
		parent_list.done = True;
	else:
		parent_list.done = False;
		
	if items_count == 0:
		parent_list.hasItem = False
		
	parent_list.save();
	
	data = {'is_removed': True, 'step_number':step_number}
	
	return JsonResponse(data)
	

#Toggle the "done" field of ToDoItem and change the "done" field of ToDoList if all the items have done or vice versa
@csrf_exempt
def item_toggle_check(request, list_id=None):
	
	todo_id = request.POST.get('todoid', None)
	
	checked_item = ToDoItem.objects.get(pk=todo_id)
	
	if checked_item.done == False:
		checked_item.done = True
		data = {'is_checked': True}
	else:
		checked_item.done = False
		data = {'is_checked': False}
	
	checked_item.save()
	
	todo_list_id = checked_item.todolist_id;
	
	items_count = ToDoItem.objects.filter(todolist_id=todo_list_id).count()
	checked_items_count = ToDoItem.objects.filter(done=True, todolist_id=todo_list_id).count()
	
	parent_list = ToDoList.objects.get(pk=checked_item.todolist_id)
	if items_count == checked_items_count:
		parent_list.done = True;
	else:
		parent_list.done = False;
		
	parent_list.save();
		
	return JsonResponse(data)
	

#Toggle the "done" field of the task
@csrf_exempt
def task_toggle_check(request, list_id=None):
	
	task_id = request.POST.get('todoid', None)
	
	checked_task = ToDoList.objects.get(pk=task_id)
	
	if checked_task.done == False:
		checked_task.done = True
		data = {'is_checked': True}
	else:
		checked_task.done = False
		data = {'is_checked': False}
	
	checked_task.save()
	
	return JsonResponse(data)

	
#To check that if the "done" field of an item is set to True or False
def item_is_checked(request):
	todo_id = request.GET.get('todoid', None)
	
	checked_item = ToDoItem.objects.get(pk=todo_id)
	
	if checked_item.done == True:
		data = {'is_checked': True}
	else:
		data = {'is_checked': False}
	
	return JsonResponse(data)

	
#To check that if the "done" field of a task is set to True or False
def task_is_checked(request):
	task_id = request.GET.get('todoid', None)
	
	checked_task = ToDoList.objects.get(pk=task_id)
	
	if checked_task.done == True:
		data = {'is_checked': True}
	else:
		data = {'is_checked': False}
	
	return JsonResponse(data)
	
	
#To get the deadline of that task and set the maximum value of dateField to that	
def get_max_date(request):
	
	task_id = request.GET.get('todoid', None)
	
	deadline = ToDoList.objects.get(pk=task_id).deadline
	
	data = {'deadline': deadline}
	
	return JsonResponse(data)

#To change the title or date of a todoitem
@csrf_exempt
def edit_item(request):
	
	new_time = request.POST.get("timeValue", None)
	new_title = request.POST.get("titleValue",None)
	new_date = request.POST.get("dateValue", None)
	
	item_id = request.POST.get("itemId", None)
		
	edited_item = ToDoItem.objects.get(pk=item_id)
	edited_item.title = new_title
	
	if new_date != "":
		edited_item.date_to_do = new_date
	
	if new_time != "":
		edited_item.time_to_do = new_time
	
	ret_data = {'new_date': edited_item.date_to_do,'new_time': edited_item.time_to_do}
	
	edited_item.save();
		
	return JsonResponse(ret_data);
	
#To make the task and its items done	
@csrf_exempt	
def task_done(request):
	
	task_id = request.POST.get('taskId', None)
	
	task = ToDoList.objects.get(pk=task_id)
	
	task.done = True
	
	task.save();
	
	
	items = ToDoItem.objects.filter(todolist_id=task_id)

	for item in items:
		item.done =True
		item.save()
	
	
	data = {'is_done': True}
	
	return JsonResponse(data)
	
#Get the task title of the given item	
def get_task_title(request):

	item_id = request.GET.get('todoid', None)
	
	task_id = ToDoItem.objects.get(pk=item_id).todolist_id
	
	task_title = ToDoList.objects.get(pk=task_id).title
	
	data = {'task_title': task_title}
	
	return JsonResponse(data)

	
def signup(request):
    
	if request.method == 'POST':
		form = SignUpForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('username')
			raw_password = form.cleaned_data.get('password1')
			user = authenticate(username=username, password=raw_password)
			messages.success(request, f'Your account has been created! You are now able to og in.')
			# login(request, user)
			return redirect('../login')
	else:
		form = SignUpForm()
    
	return render(request, 'todoapp/signup.html', {'form': form})

templates/todoapp/base.html
{% load static %}
<head>
	<link rel="stylesheet" type="text/css" href="{% static 'todoapp/styles.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'fontawesome/css/fontawesome-all.min.css' %}">
	<script src="{% static 'todoapp/jquery-3.3.1.min.js' %}"></script>
	<script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
	<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
	{% include 'todoapp/nav.html' %}
    {% block content %}{% endblock %}
</body>

templates/todoapp/general.html
{% extends 'todoapp/base.html' %}

{% block content %}

<title>
    {% block title %}General Tasks | ToDoList{% endblock %}
</title>

<div class="container">

<h1>General Tasks</h1>
<form action="" method="post" id="general">
	{% csrf_token %}
	<div class="todoFields">
		
			<span>
				<label for="title">Title</label>
				<input type="text" id="title" placeholder="I want to do..." name="title" required>
			</span>
			
			<span>
				<label for="deadline">Deadline</label>
				<input type="date" id="deadline" name="deadline" min="new Date().toISOString().split('T')[0]">
			</span>
		
			<button type="submit" name="save" class="addTask"><i></i></button>
	</div>
	
	<h3>In Progress Tasks:</h3>
	<ul class="todolist">
		{% for todo in todolist %}
			{% if not todo.done and todo.user_id == user.id %}
			<li data-id="{{todo.id}}">
				<p class="todotitle">{{todo.title}}</p>
				<span class="date">{{todo.deadline}}</span>
				
				<a href="{% url 'todoapp:items' todo.id %}" class="viewItems">Add/View<br>Task Items</a>
				<i class="fa fa-times delete" onclick="removeList({% verbatim %}this{% endverbatim %}, {{todo.id}})">
					<span class="tooltiptext">Remove The Task?</span>
				</i>
				<i class="fa fa-pencil-alt editList" onclick="startEdit({% verbatim %}this{% endverbatim %})">
					<span class="tooltiptext">Edit The Task</span>
				</i>
				<i class="fa fa-arrow-circle-down saveList" onclick="saveEdit({% verbatim %}this{% endverbatim %}, {{todo.id}})"></i>
				<i class="fa fa-check done" onclick="taskDone({% verbatim %}this{% endverbatim %},{{todo.id}})">
					<span class="tooltiptext">Task Completed?</span>
				</i>
			</li>
			{% endif %}
		{% endfor %}
	</ul>
	
	<h3>Accomplished Tasks:</h3>
	<ul class="doneList">
		{% for todo in todolist%}
			{% if todo.done and todo.user_id == user.id  %}
			<li data-id="{{todo.id}}">
				<p class="todotitle">{{todo.title}}</p>
				<div class="date">{{todo.deadline}}</div>
				<a href="{% url 'todoapp:items' todo.id %}" class="viewItems">Add/View<br>Task Items</a>
				<i class="fa fa-times delete" onclick="removeList({% verbatim %}this{% endverbatim %}, {{todo.id}})">
					<span class="tooltiptext">Remove the Task?</span>
				</i>
				<i class="fa fa-pencil-alt editList" onclick="startEdit({% verbatim %}this{% endverbatim %})">
					<span class="tooltiptext">Edit the Task</span>
				</i>
				<i class="fa fa-arrow-circle-down saveList" onclick="saveEdit({% verbatim %}this{% endverbatim %}, {{todo.id}})"></i>
			</li>
			{% endif %}
		{% endfor %}
	</ul>
	
<form>
</div>

{% block javascript %}
<script>


//set the default value and minimum date of deadline to today
let today = new Date().toISOString().substr(0, 10);
$("#deadline").val(today);
$("#deadline").attr('min',today);


//Display updated version of todolist on back button
$(window).bind("pageshow", function(event) {
    if (event.originalEvent.persisted) {
        window.location.reload(); 
    }
});

displayTooltip();

function removeList(tag, id){
	
	var csrftoken = Cookies.get('csrftoken');
	$.ajax({
		method: "POST",
		url: 'remove_list/',
        data: {
			'CSRF': csrftoken,
			'listid': id
        },
        dataType: 'json',
          
        success: function (data) {
			$(tag).parent("li").remove();
        }
    });
}


function startEdit(tag){
        
        var title = $(tag).siblings('.todotitle').text();
		var deadline =  $(tag).siblings('.date').text(); 
        
		$(tag).siblings('.saveList').addClass('active');

        var titleTag = '<input type="text" value= "' + title +'" class="titleTag"/>'
        $(tag).siblings('.todotitle').html(titleTag);
		
		var dateTag = '<input type="date" value= "' + deadline +'" class="dateTag"/>'
		$(tag).siblings('.date').html(dateTag);

        $("ul input").click(function (e) {
            e.stopPropagation();
        });
    }

    $("ul .saveList").click(function (e) {
        e.stopPropagation();
    });

	
function saveEdit(tag, id) {
	var csrftoken = Cookies.get('csrftoken');
	var titleValue = $(tag).siblings('.todotitle').find('.titleTag').val();
	var dateValue = $(tag).siblings('.date').find('.dateTag').val();
		$.ajax({
			method: "POST",
			url: 'edit_list/',
        data: {
			'CSRF': csrftoken,
			'listId': id,
			'titleValue': titleValue,
			'dateValue': dateValue
        },
        dataType: 'json',
          
        success: function (data) {
			$(tag).siblings('.todotitle').html(titleValue);
			$(tag).siblings('.date').html(data.new_date);
			$(tag).removeClass('active');
			displayTooltip();
        }
    });
}

//Make the task and its items marked as done
function taskDone(tag, taskId){
	
	var taskTitle = $(tag).siblings('.todotitle').html();
	var taskDeadline = $(tag).siblings('.date').html();
	var csrftoken = Cookies.get('csrftoken');
	$.ajax({
			method: "POST",
			url: 'task_done/',
        data: {
			'CSRF': csrftoken,
			'taskId': taskId
        },
        dataType: 'json',
          
        success: function (data) {
			$(tag).parent('li').remove();
			newTag = '<li data-id="'+taskId+'"><p class="todotitle">'+taskTitle+'</p><div class="date">'+taskDeadline+'</div><a href="/'+taskId+'" class="viewItems">View<br>Task Items</a><i class="fa fa-times delete" onclick="removeList('+{% verbatim %}this{% endverbatim %}+','+ taskId+')"></i><i class="fa fa-pencil-alt editList" onclick="startEdit('+{% verbatim %}this{% endverbatim %}+')"></i><i class="fa fa-check saveList" onclick="saveEdit('+{% verbatim %}this{% endverbatim %}, taskId+')"></i></li>';
$('.doneList').append(newTag);
        }
    });
}

function displayTooltip(){
    $('.todotitle').each(function(i) {
         if (isEllipsisActive(this))
            $(this).attr("title", $(this).text());
		else
			$(this).removeAttr("title");
    });
}

function isEllipsisActive(e) {
     return (e.offsetWidth < e.scrollWidth);
}

</script>

{% endblock %}
{% endblock %}

templates/todoapp/login.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'todoapp/styles.css' %}">
<script src="{% static 'todoapp/jquery-3.3.1.min.js' %}"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>
    {% block title %}Login | ToDoList{% endblock %}
</title>

{% load crispy_forms_tags %}
{% block content %}
<head>
	<link rel="stylesheet" type="text/css" href="{% static 'fontawesome/css/fontawesome-all.min.css' %}">
	<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-social/5.1.1/bootstrap-social.css"></script> -->
</head>
<body>
	<div class="container">
		<section id="login">
			<form method="post">
			{% csrf_token %}
			<fieldset class="form-group">
					<legend class="border-bottom mb-4">Log In</legend>
					{{form|crispy}}
				</fieldset>
			<button class="btn btn-info" type="submit">Login</button>
			</form>
			
			<br>
			<p><strong>-- OR --</strong></p>
			<a href="{% url 'social:begin' 'google-oauth2' %}">
				<img id="google-login" src="{% static 'todoapp/images/btn_google_signin.png' %}">
			</a>
		
			<div class="signup">
				Need An Account? <a href="{% url 'todoapp:signup' %}">Sign Up Now</a>
			<div>
		</section>
	</div>
</body>
{% endblock %}

templates/todoapp/logout.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'todoapp/styles.css' %}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<meta name="viewport" content="width=device-width, initial-scale=1">

<title>
    {% block title %}Logout | ToDoList{% endblock %}
</title>

{% block content %}
<body>
	<div class="container">
		<section id="logout">
			<h2>Oops! You have been logged out!</h2>
			<div class="border-top pt-3">
				<small class="text-muted">
					<a href="{% url 'todoapp:login' %}">Log In Again</a>
				</small>
			<div>
		</section>
	</div>
</body>
{% endblock %}

templates/todoapp/nav.html
<nav class="navbar-nav">
	{% if user.is_authenticated %}
		
		<a class="nav-item nav-link" href="{% url 'todoapp:logout' %}">Log Out</a>
		{% if request.get_full_path != '/' %}
			<a href="{% url 'todoapp:index'%}" class="planning">My Calendar</a>
		{% endif %}
		{% if request.get_full_path != '/general_tasks/' %}
			<a href="{% url 'todoapp:general-tasks'%}" class="planning">Keep Planning</a>
		{% endif %}
		<span><b>{{user.username}}!</b> Light Tomorrow With Today :)</span>
	{% else %}
		<a class="nav-item nav-link" href="{% url 'todoapp:login' %}">Log In</a>
		<a class="nav-item nav-link" href="{% url 'todoapp:signup' %}">Sign Up</a>
	{% endif %}
</nav>

templates/todoapp/signup.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'todoapp/styles.css' %}">
<script src="{% static 'todoapp/jquery-3.3.1.min.js' %}"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<meta name="viewport" content="width=device-width, initial-scale=1">

<title>
    {% block title %}Signup | ToDoList{% endblock %}
</title>

{% load crispy_forms_tags %}
{% block content %}
<body>
	<div class="container">
		<section id="signup" class="active">
			<form method="post">
				{% csrf_token %}
				<fieldset class="form-group">
					<legend class="border-bottom mb-4">Join Today</legend>
					{{form|crispy}}
				</fieldset>
			<button class="btn btn-info" type="submit">Sign up</button>
			</form>
			
			<br>
			<p><strong>-- OR --</strong></p>
			<a href="{% url 'social:begin' 'google-oauth2' %}">Sign up with Google</a>
			
			<div>
				Already Have An Account? <a href="{% url 'todoapp:login' %}">Sign In</a>
			<div>
		</section>
	</div>
</body>
{% endblock %}